### ISSUE TITLE
this code will not pass francinette strict mode.

### ISSUE THREAD

**Issue by alex216** [rask24/get_next_line#5]
Hi I am yliu.
I have found your code will pass the normal mode of
the following tester, however not with --strict option enabled.

https://github.com/xicodomingues/francinette/tree/master

**Comment by alex216** [comment]
I have wrote some extra code.
But can not gain pull request auth bc Im not a collaborator.

**Comment by rask24** [comment]
@alex216 
Thank you for your comment. I've added you as a collaborator to this repository. Please submit the pull request at your convenience.
